/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.net.*;
import java.util.Base64;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wassimsaoud
 */
public class send_code extends javax.swing.JFrame {
    

    Random random=new Random();
    int min=100000;
    int max=999999;
    int otp=random.nextInt((max-min)+min);

    /**
     * Creates new form login1
     */
    public send_code() {
        initComponents();
        System.out.println("Code OTP généré : " + otp);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);// Make the error label initially invisible

    }

    //txtusername.setBackground(new java.awt.Color(orange));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVer = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/WhatsApp Image 2024-04-30 at 15.27.39.jpeg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 800));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 485, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 440));

        jPanel2.setBackground(java.awt.Color.orange);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("STIXSizeTwoSym", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 0, 25, 31));

        jLabel3.setFont(new java.awt.Font("Heiti SC", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Let's verify your identity");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 328, 50));

        jLabel4.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Enter your Phone Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, 70));

        txt_num.setBackground(java.awt.Color.orange);
        txt_num.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        txt_num.setToolTipText("");
        txt_num.setBorder(null);
        txt_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numActionPerformed(evt);
            }
        });
        jPanel2.add(txt_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 220, 20));

        jLabel5.setText("ˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍ");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 230, 30));

        jLabel7.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Verify the code recieved");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 220, 20));

        txtVer.setBackground(java.awt.Color.orange);
        txtVer.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        txtVer.setBorder(null);
        txtVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerActionPerformed(evt);
            }
        });
        jPanel2.add(txtVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 220, 30));

        jLabel8.setText("ˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍˍ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 220, 50));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Invisible.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 42, 39));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Eye.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 42, 39));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Heiti SC", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Send");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 266, 34));

        jLabel9.setFont(new java.awt.Font("Heiti SC", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Please Enter your Phone Number !");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 340, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Heiti SC", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Verify");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 266, 34));

        jLabel10.setFont(new java.awt.Font("Heiti SC", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Please Enter the Recieved code !");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 260, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 430, 440));

        setSize(new java.awt.Dimension(920, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerActionPerformed

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        txtVer.setEchoChar((char) 0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setVisible(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtVer.setEchoChar((char) 8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void txt_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // This URL is used for sending messages
        String myURI = "https://api.bulksms.com/v1/messages";

        // change these values to match your own account
        String myUsername = "test_allo_allo";
        String myPassword = "Hashiramasenju2003";
        
        String number=txt_num.getText();
        
        
        if (number.isEmpty()) {
         jLabel10.setVisible(false); 
         jLabel9.setVisible(true);
         return;
        }
         if (!number.startsWith("+212") || number.length() != 13) {
        // Afficher un message d'erreur si le numéro de téléphone ne commence pas par +212 ou n'a pas une longueur de 13 caractères
        jLabel9.setText("le numéro de téléphone doit commencer par +212 et avoir une longueur de 13 caractères");
        jLabel9.setVisible(true);
        jLabel10.setVisible(false);
        return; // Sortir de la méthode sans effectuer d'autres actions
    }
       
        // the details of the message we want to send
        String myData = "{to: \""+number+"\", encoding: \"UNICODE\", body: \"votre code de verif est "+otp+"\"}";

        // if your message does not contain unicode, the "encoding" is not required:
        // String myData = "{to: \"1111111\", body: \"Hello Mr. Smith!\"}";
        // build the request based on the supplied settings
        URL url;
        try {
            url = new URL(myURI);

            HttpURLConnection request = (HttpURLConnection) url.openConnection();
            request.setDoOutput(true);

            // supply the credentials
            String authStr = myUsername + ":" + myPassword;
            String authEncoded = Base64.getEncoder().encodeToString(authStr.getBytes());
            request.setRequestProperty("Authorization", "Basic " + authEncoded);

            // we want to use HTTP POST
            request.setRequestMethod("POST");
            request.setRequestProperty("Content-Type", "application/json");

            try ( // write the data to the request
                    OutputStreamWriter out = new OutputStreamWriter(request.getOutputStream())) {
                out.write(myData);
            }

            // try ... catch to handle errors nicely
            try {
                // make the call to the API
                InputStream response = request.getInputStream();
                try (BufferedReader in = new BufferedReader(new InputStreamReader(response))) {
                    String replyText;
                    while ((replyText = in.readLine()) != null) {
                        System.out.println(replyText);
                    }
                }
            } catch (IOException ex) {
                System.out.println("An error occurred:" + ex.getMessage());
                // print the detail that comes with the error
                try (BufferedReader in = new BufferedReader(new InputStreamReader(request.getErrorStream()))) {
                    // print the detail that comes with the error
                    String replyText;
                    while ((replyText = in.readLine()) != null) {
                        System.out.println(replyText);
                    }
                }
            }
            request.disconnect();
        } catch (MalformedURLException ex) {
            Logger.getLogger(send_code.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(send_code.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        /**
          String usernameOrEmail = txtEmail.getText(); String password = new
         * String(txtVer.getPassword());
         *
         * if (usernameOrEmail.isEmpty() || password.isEmpty()) {
         * jLabel10.setVisible(true); jLabel9.setVisible(false); if
         * (usernameOrEmail.isEmpty() && password.isEmpty()) {
         * jLabel10.setText("Please enter username/email and password");
         * jLabel9.setVisible(false); } else if (usernameOrEmail.isEmpty()) {
         * jLabel10.setText("Please enter username/email");
         * jLabel9.setVisible(false); } else { jLabel10.setText("Please enter
         * password"); jLabel9.setVisible(false); } return; // Exit the method
         * to prevent further execution }
         *
         * try (Connection conn = connection_BD.getConnection()) {
         * PreparedStatement stmt = conn.prepareStatement("SELECT Role_User FROM
         * users WHERE (Email_User = ? OR Nom_User = ?) AND Mots_de_passe_User =
         * ?"); stmt.setString(1, usernameOrEmail); stmt.setString(2,
         * usernameOrEmail); stmt.setString(3, password); ResultSet rs =
         * stmt.executeQuery();
         *
         * if (rs.next()) { String role = rs.getString("Role_User"); switch
         * (role) { case "Admin": new AdminPage().setVisible(true);
         * this.dispose(); // close the login window break; case "User": new
         * UserHome().setVisible(true); this.dispose(); break; case "Chef": new
         * ChefPage().setVisible(true); this.dispose(); break; default:
         * JOptionPane.showMessageDialog(this, "Invalid Role"); break; } } else
         * { //JOptionPane.showMessageDialog(this, "Invalid username(Email) or
         * password"); jLabel9.setVisible(true); jLabel10.setVisible(false);
         *
         * }
         * } catch (SQLException e) { e.printStackTrace();
         * JOptionPane.showMessageDialog(this, "Error connecting to the
         * database"); }  *
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codeVerf= new String(txtVer.getPassword());
        if (codeVerf.isEmpty()) {
         jLabel10.setVisible(true); 
         jLabel9.setVisible(false);
         return;
        }
        int userCode = Integer.parseInt(codeVerf);
        if (userCode == otp) {
        // Le code est correct
        // Faire ce que vous avez besoin de faire ici si le code est correct
        jLabel10.setVisible(false); // Masquer le message d'erreur
        jLabel9.setVisible(false);
        String number=txt_num.getText();
        String phoneNumber=number;
         dispose();
         Reset_passwd pd=new Reset_passwd(phoneNumber);
    //this.setVisible(false);
        pd.setVisible(true);
        return;
        
    } else {
        // Le code est incorrect
        // Afficher un message d'erreur
        jLabel10.setText("Le code est incorrect. Veuillez réessayer");
        jLabel10.setVisible(true);
        jLabel9.setVisible(false);
        //JOptionPane.showMessageDialog(this, "Le code est incorrect. Veuillez réessayer.");
        
    }
    
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(send_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(send_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(send_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(send_code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new send_code().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtVer;
    private javax.swing.JTextField txt_num;
    // End of variables declaration//GEN-END:variables
}
