package Admin;


import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class mainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form mainAdmin
     */
    
    public final Color DefaultColor = new Color(255, 204, 51);
    public final Color ClickedColor = new Color(240, 151, 57);
    private ImageIcon headerImage;
    private itemsPanel itemsPanelInstance;
    private boolean itemsPanelAdded = false;
    private accountsPanel accountsPanelInstance;
    private boolean accountsPanelAdded = false;
    private mealsPanel mealsPanelInstance;
    private boolean mealsPanelAdded = false;

    public mainAdmin() {
        initComponents();
        
    }
    
    public void setColorLabel(JLabel label){
        label.setForeground(new Color(242,242,242));
    }
    public void resetColorLabel(JLabel label1, JLabel label2, JLabel label3, JLabel label4){
        label1.setForeground(new Color(0,0,0)); 
        label2.setForeground(new Color(0,0,0));
        label3.setForeground(new Color(0,0,0));
        label4.setForeground(new Color(0,0,0));
        
    }
    public void setdotImg(Component img){
        img.setVisible(true);
    }
    public void resetdotImg(JLabel img1, JLabel img2, JLabel img3, JLabel img4){
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(false);
    }
    public void colorClicked(Component pnl){
        pnl.setBackground(ClickedColor);
    }
    public void colorDefault(JPanel pnl1, JPanel pnl2, JPanel pnl3, JPanel pnl4){
        pnl1.setBackground(DefaultColor);
        pnl2.setBackground(DefaultColor);
        pnl3.setBackground(DefaultColor);
        pnl4.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashBoard = new javax.swing.JPanel();
        helloAdmin = new javax.swing.JLabel();
        logoutPanelDash = new javax.swing.JPanel();
        dotImgLogout = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        accountsPanelDash = new javax.swing.JPanel();
        dotImgAccounts = new javax.swing.JLabel();
        accountsLabel = new javax.swing.JLabel();
        itemsPanelDash = new javax.swing.JPanel();
        dotImgItems = new javax.swing.JLabel();
        ItemsLabel = new javax.swing.JLabel();
        mealsPanelDash = new javax.swing.JPanel();
        dotImgMeals = new javax.swing.JLabel();
        MealsLabel = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        headerPanel = new JImagePanel(new ImageIcon("C:\\Users\\PC\\Pictures\\img_projet\\BackgroundImg.png").getImage());
        menuPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        DashBoard.setBackground(new java.awt.Color(255, 204, 51));
        DashBoard.setMaximumSize(new java.awt.Dimension(319, 2147483647));

        helloAdmin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        helloAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-account-24.png")));
        helloAdmin.setText("Hello, Admin");

        logoutPanelDash.setBackground(new java.awt.Color(153, 153, 255));
        logoutPanelDash.setPreferredSize(new java.awt.Dimension(138, 40));
        logoutPanelDash.setVerifyInputWhenFocusTarget(false);
        logoutPanelDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelDashMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutPanelDashMousePressed(evt);
            }
        });

        dotImgLogout.setBackground(new java.awt.Color(204, 204, 204));
        dotImgLogout.setForeground(new java.awt.Color(204, 204, 204));
        dotImgLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-dot-24.png")));

        logoutLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/logout.png")));
        logoutLabel.setText("Log out");

        javax.swing.GroupLayout logoutPanelDashLayout = new javax.swing.GroupLayout(logoutPanelDash);
        logoutPanelDash.setLayout(logoutPanelDashLayout);
        logoutPanelDashLayout.setHorizontalGroup(
            logoutPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelDashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dotImgLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutPanelDashLayout.setVerticalGroup(
            logoutPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelDashLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(dotImgLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        accountsPanelDash.setBackground(new java.awt.Color(153, 153, 255));
        accountsPanelDash.setPreferredSize(new java.awt.Dimension(134, 40));
        accountsPanelDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsPanelDashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountsPanelDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountsPanelDashMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountsPanelDashMousePressed(evt);
            }
        });

        dotImgAccounts.setBackground(new java.awt.Color(204, 204, 204));
        dotImgAccounts.setForeground(new java.awt.Color(204, 204, 204));
        dotImgAccounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-dot-24.png")));

        accountsLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        accountsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/Accounts.png")));
        accountsLabel.setText("Accounts");

        javax.swing.GroupLayout accountsPanelDashLayout = new javax.swing.GroupLayout(accountsPanelDash);
        accountsPanelDash.setLayout(accountsPanelDashLayout);
        accountsPanelDashLayout.setHorizontalGroup(
            accountsPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelDashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dotImgAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountsPanelDashLayout.setVerticalGroup(
            accountsPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountsPanelDashLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(dotImgAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itemsPanelDash.setBackground(new java.awt.Color(153, 153, 255));
        itemsPanelDash.setPreferredSize(new java.awt.Dimension(134, 40));
        itemsPanelDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemsPanelDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemsPanelDashMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemsPanelDashMousePressed(evt);
            }
        });

        dotImgItems.setBackground(new java.awt.Color(204, 204, 204));
        dotImgItems.setForeground(new java.awt.Color(204, 204, 204));
        dotImgItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-dot-24.png")));

        ItemsLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        ItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-open-box-24.png")));
        ItemsLabel.setText("Items");
        ItemsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemsLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout itemsPanelDashLayout = new javax.swing.GroupLayout(itemsPanelDash);
        itemsPanelDash.setLayout(itemsPanelDashLayout);
        itemsPanelDashLayout.setHorizontalGroup(
            itemsPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelDashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dotImgItems, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemsPanelDashLayout.setVerticalGroup(
            itemsPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelDashLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(dotImgItems, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mealsPanelDash.setBackground(new java.awt.Color(153, 153, 255));
        mealsPanelDash.setPreferredSize(new java.awt.Dimension(134, 40));
        mealsPanelDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealsPanelDashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mealsPanelDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mealsPanelDashMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mealsPanelDashMousePressed(evt);
            }
        });

        dotImgMeals.setBackground(new java.awt.Color(204, 204, 204));
        dotImgMeals.setForeground(new java.awt.Color(204, 204, 204));
        dotImgMeals.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-dot-24.png")));

        MealsLabel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        MealsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/icons8-vegan-food-32.png")));
        MealsLabel.setText("Meals");

        javax.swing.GroupLayout mealsPanelDashLayout = new javax.swing.GroupLayout(mealsPanelDash);
        mealsPanelDash.setLayout(mealsPanelDashLayout);
        mealsPanelDashLayout.setHorizontalGroup(
            mealsPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealsPanelDashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dotImgMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MealsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mealsPanelDashLayout.setVerticalGroup(
            mealsPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MealsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealsPanelDashLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(dotImgMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(helloAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoutPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
            .addComponent(mealsPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
            .addComponent(itemsPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
            .addComponent(accountsPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(helloAdmin)
                .addGap(44, 44, 44)
                .addComponent(accountsPanelDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemsPanelDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mealsPanelDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(logoutPanelDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(DashBoard);

        panel2.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(204, 204, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(449, 50));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panel2.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        menuPanel.setBackground(new java.awt.Color(255, 0, 0));
        menuPanel.setLayout(new javax.swing.BoxLayout(menuPanel, javax.swing.BoxLayout.LINE_AXIS));
        panel2.add(menuPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutPanelDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelDashMouseEntered
        // TODO add your handling code here:
        colorClicked(logoutPanelDash);

        setdotImg(dotImgLogout);

        setColorLabel(logoutLabel );
    }//GEN-LAST:event_logoutPanelDashMouseEntered

    private void logoutPanelDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelDashMouseExited
        // TODO add your handling code here:
        colorDefault(logoutPanelDash,itemsPanelDash,mealsPanelDash,accountsPanelDash);

        resetdotImg(dotImgLogout,dotImgItems,dotImgAccounts,dotImgMeals);

        resetColorLabel(logoutLabel,ItemsLabel,accountsLabel,MealsLabel
        );

    }//GEN-LAST:event_logoutPanelDashMouseExited

    private void logoutPanelDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelDashMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutPanelDashMousePressed

    private void accountsPanelDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsPanelDashMouseEntered
        // TODO add your handling code here:
       /* colorClicked(accountsPanelDash);

        setdotImg(dotImgAccounts);

        setColorLabel(accountsLabel );*/
    }//GEN-LAST:event_accountsPanelDashMouseEntered

    private void accountsPanelDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsPanelDashMouseExited
        // TODO add your handling code here:
        /*colorDefault(logoutPanelDash,itemsPanelDash,accountsPanelDash,mealsPanelDash);

        resetdotImg(dotImgLogout,dotImgItems,dotImgAccounts,dotImgMeals);

        resetColorLabel(logoutLabel,ItemsLabel,accountsLabel,MealsLabel);*/
    }//GEN-LAST:event_accountsPanelDashMouseExited

    private void accountsPanelDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsPanelDashMousePressed
            
        
    }//GEN-LAST:event_accountsPanelDashMousePressed

    private void itemsPanelDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsPanelDashMouseEntered
        // TODO add your handling code here:
       /* colorClicked(itemsPanelDash);

        setdotImg(dotImgItems);

        setColorLabel(ItemsLabel );*/
    }//GEN-LAST:event_itemsPanelDashMouseEntered

    private void itemsPanelDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsPanelDashMouseExited
        // TODO add your handling code here:
       /* colorDefault(logoutPanelDash,itemsPanelDash,mealsPanelDash,accountsPanelDash);

        resetdotImg(dotImgLogout,dotImgItems,dotImgAccounts,dotImgMeals);

        resetColorLabel(logoutLabel,ItemsLabel,accountsLabel,MealsLabel
        );*/
    }//GEN-LAST:event_itemsPanelDashMouseExited

    private void itemsPanelDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsPanelDashMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemsPanelDashMousePressed

    private void mealsPanelDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsPanelDashMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mealsPanelDashMouseEntered

    private void mealsPanelDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsPanelDashMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mealsPanelDashMouseExited

    private void mealsPanelDashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsPanelDashMousePressed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_mealsPanelDashMousePressed

    private void mealsPanelDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsPanelDashMouseClicked
        // TODO add your handling code here:
        if (!mealsPanelAdded) {
            // Create instances of the itemsPanel and mealsPanel
            mealsPanelInstance = new mealsPanel();
            // Remove the itemsPanel and mealsPanel from the menuPanel
            menuPanel.add(mealsPanelInstance);
            mealsPanelAdded = true;
            colorClicked(mealsPanelDash);
            setdotImg(dotImgMeals);
            setColorLabel(MealsLabel );
        }else{
            menuPanel.remove(mealsPanelInstance);
            mealsPanelAdded = false;
            mealsPanelDash.setBackground(DefaultColor);
            dotImgMeals.setVisible(false);
            MealsLabel.setForeground(new Color(0,0,0)); 
        }
    }//GEN-LAST:event_mealsPanelDashMouseClicked

    private void ItemsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsLabelMouseClicked
        // TODO add your handling code here:
        if (!itemsPanelAdded) {
            // Create an instance of the itemsPanel
            itemsPanelInstance = new itemsPanel();
            // Add the itemsPanel to the menuPanel
            menuPanel.add(itemsPanelInstance);
            // Update the flag to indicate that the items panel is added
            itemsPanelAdded = true;
            // Optionally, you can add additional visual feedback here
            colorClicked(itemsPanelDash);
            setdotImg(dotImgItems);
            setColorLabel(ItemsLabel);
        } else {
            // If the items panel is already added, remove it from the menuPanel
            menuPanel.remove(itemsPanelInstance);
            // Update the flag to indicate that the items panel is not added
            itemsPanelAdded = false;
            // Optionally, reset visual feedback for the items panel
            itemsPanelDash.setBackground(DefaultColor);
            dotImgItems.setVisible(false);
            ItemsLabel.setForeground(new Color(0,0,0));     
}

    }//GEN-LAST:event_ItemsLabelMouseClicked

    private void accountsPanelDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsPanelDashMouseClicked
        // TODO add your handling code here:
        if (!accountsPanelAdded) {
            // Create instances of the itemsPanel and mealsPanel
            accountsPanelInstance = new accountsPanel();
            // Remove the itemsPanel and mealsPanel from the menuPanel
            menuPanel.add(accountsPanelInstance);
            accountsPanelAdded = true;
            colorClicked(accountsPanelDash);
            setdotImg(dotImgAccounts);
            setColorLabel(accountsLabel );
        }else{
            menuPanel.remove(accountsPanelInstance);
            accountsPanelAdded = false;
            accountsPanelDash.setBackground(DefaultColor);
            dotImgAccounts.setVisible(false);
            accountsLabel.setForeground(new Color(0,0,0)); 
        }
    }//GEN-LAST:event_accountsPanelDashMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainAdmin().setVisible(true);
            }
        });
    }
    private static class JImagePanel extends JPanel {

        private Image image;

        public JImagePanel(Image image) {
            this.image = image;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (image != null) {
                g.drawImage(image, 0, 0, this);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashBoard;
    private javax.swing.JLabel ItemsLabel;
    private javax.swing.JLabel MealsLabel;
    private javax.swing.JLabel accountsLabel;
    private javax.swing.JPanel accountsPanelDash;
    private javax.swing.JLabel dotImgAccounts;
    private javax.swing.JLabel dotImgItems;
    private javax.swing.JLabel dotImgLogout;
    private javax.swing.JLabel dotImgMeals;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel helloAdmin;
    private javax.swing.JPanel itemsPanelDash;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutPanelDash;
    private javax.swing.JPanel mealsPanelDash;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
