package Admin;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Admin.customButton.Button;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author PC
 */
public class mealsPanel extends javax.swing.JPanel {

    /**
     * Creates new form mealsPanel
     */
    private ImageIcon headerImage;
    private itemsPanel itemsPanelInstance;;
    public mealsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        mealsPanel = new javax.swing.JPanel();
        mealsTxtField = new javax.swing.JTextField();
        mealsScrollPane = new javax.swing.JScrollPane();
        mealsList = new javax.swing.JList<>();
        mealsButtonPanel = new JImagePanel(new ImageIcon("C:\\Users\\PC\\Pictures\\img_projet\\unsplash.jpg").getImage());
        mealsAjouterButton = new Button();
        mealsSupprimerButton = new Button();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mealsFormPanel = new javax.swing.JPanel();
        PanelX = new JImagePanel(new ImageIcon("C:\\Users\\PC\\Pictures\\img_projet\\karabous1.png").getImage());
        mealNomLabel1 = new javax.swing.JLabel();
        mealDailyLabel1 = new javax.swing.JLabel();
        mealNomTxtField1 = new javax.swing.JTextField();
        mealDateDebutLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mealDesAreaTxt1 = new javax.swing.JTextArea();
        mealDesLabel1 = new javax.swing.JLabel();
        mealDateDebutTxtField1 = new javax.swing.JTextField();
        mealDateFinLabel1 = new javax.swing.JLabel();
        mealDateFinTxtField1 = new javax.swing.JTextField();
        mealValiderButton1 = new Button();
        mealResetButton1 = new javax.swing.JButton();
        mealResetButton = new Button();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel5 = new JImagePanel(new ImageIcon("C:\\Users\\PC\\Pictures\\img_projet\\Blackboard3.png").getImage());

        setPreferredSize(new java.awt.Dimension(639, 300));
        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        mealsPanel.setBackground(new java.awt.Color(153, 153, 153));
        mealsPanel.setInheritsPopupMenu(true);
        mealsPanel.setMaximumSize(new java.awt.Dimension(400, 306));
        mealsPanel.setMinimumSize(new java.awt.Dimension(400, 306));
        mealsPanel.setPreferredSize(new java.awt.Dimension(400, 306));
        mealsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mealsPanelMouseEntered(evt);
            }
        });
        mealsPanel.setLayout(new java.awt.BorderLayout());

        mealsTxtField.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealsTxtField.setText("search Meal");
        mealsPanel.add(mealsTxtField, java.awt.BorderLayout.PAGE_START);

        mealsList.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mealsScrollPane.setViewportView(mealsList);

        mealsPanel.add(mealsScrollPane, java.awt.BorderLayout.CENTER);

        mealsButtonPanel.setBackground(new java.awt.Color(153, 153, 153));
        mealsButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealsButtonPanelMouseClicked(evt);
            }
        });

        mealsAjouterButton.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealsAjouterButton.setText("Ajouter Meal");
        mealsAjouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsAjouterButtonActionPerformed(evt);
            }
        });

        mealsSupprimerButton.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealsSupprimerButton.setText("Supprimer Meal");

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mealsW.png"))); // NOI18N
        jLabel1.setText("Meals");

        javax.swing.GroupLayout mealsButtonPanelLayout = new javax.swing.GroupLayout(mealsButtonPanel);
        mealsButtonPanel.setLayout(mealsButtonPanelLayout);
        mealsButtonPanelLayout.setHorizontalGroup(
            mealsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealsButtonPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(mealsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mealsSupprimerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mealsAjouterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        mealsButtonPanelLayout.setVerticalGroup(
            mealsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealsButtonPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(mealsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mealsButtonPanelLayout.createSequentialGroup()
                        .addComponent(mealsAjouterButton)
                        .addGap(18, 18, 18)
                        .addComponent(mealsSupprimerButton)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        mealsPanel.add(mealsButtonPanel, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(mealsPanel, "card3");

        mealsFormPanel.setLayout(new javax.swing.BoxLayout(mealsFormPanel, javax.swing.BoxLayout.Y_AXIS));

        PanelX.setBackground(new java.awt.Color(102, 153, 0));
        PanelX.setMaximumSize(new java.awt.Dimension(32767, 300));
        PanelX.setMinimumSize(new java.awt.Dimension(400, 300));
        PanelX.setName(""); // NOI18N
        PanelX.setOpaque(false);
        PanelX.setPreferredSize(new java.awt.Dimension(499, 300));

        mealNomLabel1.setBackground(new java.awt.Color(255, 204, 51));
        mealNomLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealNomLabel1.setText("Nom : ");
        mealNomLabel1.setOpaque(true);

        mealDailyLabel1.setBackground(new java.awt.Color(255, 204, 51));
        mealDailyLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealDailyLabel1.setText("Is Daily");
        mealDailyLabel1.setOpaque(true);

        mealNomTxtField1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealNomTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealNomTxtField1ActionPerformed(evt);
            }
        });

        mealDateDebutLabel1.setBackground(new java.awt.Color(255, 204, 51));
        mealDateDebutLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealDateDebutLabel1.setText("Date debut");
        mealDateDebutLabel1.setOpaque(true);

        mealDesAreaTxt1.setColumns(20);
        mealDesAreaTxt1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealDesAreaTxt1.setRows(5);
        jScrollPane3.setViewportView(mealDesAreaTxt1);

        mealDesLabel1.setBackground(new java.awt.Color(255, 204, 51));
        mealDesLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealDesLabel1.setText("Description :");
        mealDesLabel1.setOpaque(true);

        mealDateDebutTxtField1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealDateDebutTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealDateDebutTxtField1ActionPerformed(evt);
            }
        });

        mealDateFinLabel1.setBackground(new java.awt.Color(255, 204, 51));
        mealDateFinLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealDateFinLabel1.setText("Date Fin");
        mealDateFinLabel1.setOpaque(true);

        mealDateFinTxtField1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealDateFinTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealDateFinTxtField1ActionPerformed(evt);
            }
        });

        mealValiderButton1.setBackground(new java.awt.Color(255, 204, 51));
        mealValiderButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealValiderButton1.setText("Valider");
        mealValiderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealValiderButton1ActionPerformed(evt);
            }
        });

        mealResetButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        mealResetButton1.setText("Reset");

        mealResetButton.setBackground(java.awt.Color.black);
        mealResetButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        mealResetButton.setForeground(java.awt.Color.white);
        mealResetButton.setText("Reset");
        mealResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealResetButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setText("oui");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setText("non");

        javax.swing.GroupLayout PanelXLayout = new javax.swing.GroupLayout(PanelX);
        PanelX.setLayout(PanelXLayout);
        PanelXLayout.setHorizontalGroup(
            PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelXLayout.createSequentialGroup()
                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelXLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mealDateDebutLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mealNomLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mealDesLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(mealDailyLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelXLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mealDateFinLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mealDateFinTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelXLayout.createSequentialGroup()
                                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelXLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mealNomTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelXLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jRadioButton2))
                                    .addGroup(PanelXLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mealDateDebutTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelXLayout.createSequentialGroup()
                                                .addComponent(mealResetButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(mealValiderButton1)))))
                                .addGap(24, 24, 24))))
                    .addGroup(PanelXLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(mealResetButton1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PanelXLayout.setVerticalGroup(
            PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelXLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealNomLabel1)
                    .addComponent(mealNomTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mealDesLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mealDailyLabel1)
                        .addComponent(jRadioButton2)))
                .addGap(18, 18, 18)
                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealDateDebutTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealDateDebutLabel1)
                    .addComponent(mealDateFinLabel1)
                    .addComponent(mealDateFinTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealValiderButton1)
                    .addComponent(mealResetButton))
                .addGap(137, 137, 137)
                .addComponent(mealResetButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mealsFormPanel.add(PanelX);

        jPanel5.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        mealsFormPanel.add(jPanel5);

        jPanel1.add(mealsFormPanel, "card4");

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void mealsAjouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsAjouterButtonActionPerformed
        // TODO add your handling code here:
        mealsPanel.setVisible(false);
        mealsFormPanel.setVisible(true);
    }//GEN-LAST:event_mealsAjouterButtonActionPerformed

    private void mealsButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsButtonPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mealsButtonPanelMouseClicked

    private void mealsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mealsPanelMouseClicked

    private void mealsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mealsPanelMouseEntered

    private void mealValiderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealValiderButton1ActionPerformed
        // TODO add your handling code here:
        mealsFormPanel.setVisible(false);
        mealsPanel.setVisible(true);
    }//GEN-LAST:event_mealValiderButton1ActionPerformed

    private void mealNomTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealNomTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealNomTxtField1ActionPerformed

    private void mealResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealResetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealResetButtonActionPerformed

    private void mealDateFinTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealDateFinTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealDateFinTxtField1ActionPerformed

    private void mealDateDebutTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealDateDebutTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealDateDebutTxtField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private static class JImagePanel extends JPanel {

        private Image image;

        public JImagePanel(Image image) {
            this.image = image;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (image != null) {
                g.drawImage(image, 0, 0, this);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelX;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mealDailyLabel1;
    private javax.swing.JLabel mealDateDebutLabel1;
    private javax.swing.JTextField mealDateDebutTxtField1;
    private javax.swing.JLabel mealDateFinLabel1;
    private javax.swing.JTextField mealDateFinTxtField1;
    private javax.swing.JTextArea mealDesAreaTxt1;
    private javax.swing.JLabel mealDesLabel1;
    private javax.swing.JLabel mealNomLabel1;
    private javax.swing.JTextField mealNomTxtField1;
    private javax.swing.JButton mealResetButton;
    private javax.swing.JButton mealResetButton1;
    private javax.swing.JButton mealValiderButton1;
    private javax.swing.JButton mealsAjouterButton;
    private javax.swing.JPanel mealsButtonPanel;
    private javax.swing.JPanel mealsFormPanel;
    private javax.swing.JList<String> mealsList;
    private javax.swing.JPanel mealsPanel;
    private javax.swing.JScrollPane mealsScrollPane;
    private javax.swing.JButton mealsSupprimerButton;
    private javax.swing.JTextField mealsTxtField;
    // End of variables declaration//GEN-END:variables
}
